# Generated by Django 5.1.6 on 2025-02-10 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('first_address', models.CharField(max_length=100)),
                ('second_address', models.CharField(blank=True, max_length=100, null=True)),
                ('county', models.CharField(choices=[('Ant', 'Antrim'), ('Arm', 'Armagh'), ('Car', 'Carlow'), ('Cav', 'Cavan'), ('Cla', 'Clare'), ('Cor', 'Cork'), ('Der', 'Derry'), ('Don', 'Donegal'), ('Dow', 'Down'), ('Dub', 'Dublin'), ('Fer', 'Fermanagh'), ('Gal', 'Galway'), ('Ker', 'Kerry'), ('Kil', 'Kildare'), ('Kil', 'Kilkenny'), ('Lao', 'Laois'), ('Lei', 'Leitrim'), ('Lim', 'Limerick'), ('Lon', 'Longford'), ('Lou', 'Louth'), ('May', 'Mayo'), ('Mea', 'Meath'), ('Mon', 'Monaghan'), ('Off', 'Offaly'), ('Ros', 'Roscommon'), ('Sli', 'Sligo'), ('Tip', 'Tipperary'), ('Tyr', 'Tyrone'), ('Wat', 'Waterford'), ('Wes', 'Westmeath'), ('Wex', 'Wexford'), ('Wic', 'Wicklow')], max_length=50)),
                ('town', models.CharField(max_length=50)),
                ('eircode', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheese', models.CharField(default='Mozarella', max_length=50)),
                ('price', models.FloatField(default=0.5)),
            ],
        ),
        migrations.CreateModel(
            name='Crust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crust', models.CharField(default='Normal', max_length=50)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sauce', models.CharField(default='Tomato', max_length=50)),
                ('price', models.FloatField(default=0.5)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(default='Small', max_length=50)),
                ('price', models.FloatField(default=9.5)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pizza_App.cheese')),
                ('crust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pizza_App.crust')),
                ('sauce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pizza_App.sauce')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pizza_App.size')),
                ('topping', models.ManyToManyField(blank=True, default=None, to='Pizza_App.topping')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pizza_App.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pizza', models.ManyToManyField(to='Pizza_App.pizza')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pizzas', models.ManyToManyField(blank=True, to='Pizza_App.pizza')),
            ],
        ),
    ]
