# Generated by Django 5.1.6 on 2025-02-11 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza_App', '0002_alter_address_id_alter_cart_id_alter_cheese_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Pizza_App.size'),
        ),
    ]
