# Generated by Django 5.1.6 on 2025-02-11 22:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza_App', '0004_rename_orders_order_alter_pizza_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_card_owner', models.CharField(max_length=100)),
                ('card_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999999)])),
                ('cvv', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)])),
                ('expiry_month', models.IntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(2)])),
                ('expiry_year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(2025)])),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='county',
        ),
    ]
