# Generated by Django 5.1.6 on 2025-02-12 14:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza_App', '0005_payment_model_remove_address_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_ordered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
