# Generated by Django 5.1.5 on 2025-02-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza_App', '0006_order_time_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='topping',
            field=models.ManyToManyField(blank=True, to='Pizza_App.topping'),
        ),
    ]
